hubee:
  host: 'https://api.hubee.fr'
  auth_url: 'https://auth.api.hubee.fr'
  client_id: 'hubee_client_id'
  client_secret: 'hubee_client_secret'
responsable_traitement_attributes_idf:
  given_name: "Prénom"
  family_name: "Nom"
  email: "prenom.nom@iledefrance.fr"
  phone_number: "0636656565"
  job: "Directeur de la donnée"
  user_id: 9001
insee_client_id: insee_client_id
insee_client_secret: insee_client_secret
insee_username: insee_username
insee_password: insee_password

