:concurrency: 5
:timeout: 25
:queues:
  - 'default'
  - 'mailers'
  - 'webhooks'
  - 'reminders'
  - 'archive'
:production:
  :concurrency: <%= ENV['SIDEKIQ_CONCURRENCY'] || 5 %>

:scheduler:
  :schedule: []
