---
- name: Copy server apps deploy scripts
  copy:
    dest: "~/deploy-server-app.sh"
    src: "{{ playbook_dir }}/scripts/deploy-server-app.sh"
    mode: 0770
  become: yes
  become_user: "{{ app_user }}"

- name: Copy static apps deploy scripts
  copy:
    dest: "~/deploy-static-app.sh"
    src: "{{ playbook_dir }}/scripts/deploy-static-app.sh"
    mode: 0700
  become: yes
  become_user: "{{ app_user }}"

- name: Add ssh deployment key
  authorized_key:
    state: present
    user: "{{ app_user }}"
    key: "{{ github_action_ssh_key }}"
    key_options: 'command="{{ github_action_authorized_command }}",no-port-forwarding,no-X11-forwarding,no-agent-forwarding,no-pty' # copied from https://gitlab.com/etalab/api.gouv.fr/annuaire-entreprises-infrastructure/-/blob/main/roles/team-ssh-keys/tasks/main.yml#L21
