source "https://rubygems.org"

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

ruby "3.2.0"

gem "carrierwave"
gem "carrierwave-i18n"
gem "devise"
gem "http"
gem "kaminari"
gem "omniauth-oauth2"
gem "paper_trail"
gem "pg"
gem "puma"
gem "pundit"
gem "redis"
gem "rack-cors"
gem "rails", "~> 7.0"
gem "rails-i18n"
gem "sentry-ruby"
gem "sentry-rails"
gem "sib-api-v3-sdk"
gem "sidekiq", "~> 6.5"
gem "sidekiq-scheduler", "~> 4.0", ">= 4.0.3"
gem "state_machines-activerecord"

group :test do
  gem "db-query-matchers"
  gem "timecop"
end

group :development, :test do
  gem "factory_bot_rails"
  gem "rspec-rails"
  gem "simplecov"
  gem "standard"
  gem "webmock"
  gem "dotenv-rails"
  gem "byebug"
  gem "guard-rspec", require: false
  gem "guard-standardrb"
  gem "brakeman"
end

group :development do
  gem "listen", ">= 3.0.5", "< 3.8"
  gem "standardrb"
  gem "foreman"
  gem "rubocop"
end

gem "active_model_serializers", "~> 0.10.13"
