---
- name: Enable UFW and close all ports (DO NOT INTERRUPT!!!)
  ufw:
    state: enabled
    policy: deny
# NB. if the playbook stop here you will loss access to your server.

- name: allow all access to allowed tcp
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  with_items:
    - 22
    - 80
    - 443
    - 9000
