---
- name: Add users ssh key
  authorized_key:
    state: "{{ item.state }}"
    user: "{{ ansible_user }}"
    key: "{{ item.public_key }}"
  with_items: "{{ team_ssh_keys }}"

- name: Add users ssh key
  authorized_key:
    state: "{{ item.state }}"
    user: "{{ app_user }}"
    key: "{{ item.public_key }}"
  with_items: "{{ team_ssh_keys }}"

- name: Disable empty password login
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#?PermitEmptyPasswords"
    line: "PermitEmptyPasswords no"
  notify: restart sshd

- name: Disable remote root login
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#?PermitRootLogin"
    line: "PermitRootLogin no"
  notify: restart sshd

- name: Disable password login
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^(#\s*)?PasswordAuthentication '
    line: "PasswordAuthentication no"
  notify: restart sshd

- name: Enable PAM
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#?UsePAM"
    line: "UsePAM yes"
  notify: restart sshd
