module EntrepriseDataPayloadHelpers
  include WebMock::API

  def stub_entreprise_data_etablissement_call(siret)
    stub_request(:get, "https://entreprise.data.gouv.fr/api/sirene/v3/etablissements/#{siret}").to_return(
      status: 200,
      headers: {
        "Content-Type" => "application/json"
      },
      body: entreprise_data_etablissement_payload(siret).to_json
    )
  end

  def entreprise_data_etablissement_payload(siret)
    case siret
    when "21920023500014"
      {
        "etablissement" =>
          {
            "id" => 1585057487,
            "siren" => "219200235",
            "nic" => "00014",
            "siret" => "21920023500014",
            "statut_diffusion" => "O",
            "date_creation" => "1983-03-01",
            "tranche_effectifs" => "41",
            "annee_effectifs" => "2019",
            "activite_principale_registre_metiers" => nil,
            "date_dernier_traitement" => "2021-10-27T08=>11=>21",
            "etablissement_siege" => "true",
            "nombre_periodes" => "3",
            "complement_adresse" => "MAIRIE DE CLAMART",
            "numero_voie" => "1",
            "indice_repetition" => nil,
            "type_voie" => "PL",
            "libelle_voie" => "MAURICE GUNSBOURG",
            "code_postal" => "92140",
            "libelle_commune" => "CLAMART",
            "libelle_commune_etranger" => nil,
            "distribution_speciale" => nil,
            "code_commune" => "92023",
            "code_cedex" => "92141",
            "libelle_cedex" => "CLAMART CEDEX",
            "code_pays_etranger" => nil,
            "libelle_pays_etranger" => nil,
            "complement_adresse_2" => nil,
            "numero_voie_2" => nil,
            "indice_repetition_2" => nil,
            "type_voie_2" => nil,
            "libelle_voie_2" => nil,
            "code_postal_2" => nil,
            "libelle_commune_2" => nil,
            "libelle_commune_etranger_2" => nil,
            "distribution_speciale_2" => nil,
            "code_commune_2" => nil,
            "code_cedex_2" => nil,
            "libelle_cedex_2" => nil,
            "code_pays_etranger_2" => nil,
            "libelle_pays_etranger_2" => nil,
            "date_debut" => "2008-01-01",
            "etat_administratif" => "A",
            "enseigne_1" => "MAIRIE",
            "enseigne_2" => nil,
            "enseigne_3" => nil,
            "denomination_usuelle" => nil,
            "activite_principale" => "84.11Z",
            "nomenclature_activite_principale" => "NAFRev2",
            "caractere_employeur" => "O",
            "longitude" => "2.26263",
            "latitude" => "48.800409",
            "geo_score" => "0.88",
            "geo_type" => "housenumber",
            "geo_adresse" => "1 Place Maurice Gunsbourg 92140 Clamart",
            "geo_id" => "92023_6195_00001",
            "geo_ligne" => "G",
            "geo_l4" => "1 PLACE MAURICE GUNSBOURG",
            "geo_l5" => nil,
            "created_at" => "2022-04-03T05=>09=>36.298+02=>00",
            "updated_at" => "2022-04-03T05=>09=>36.298+02=>00",
            "unite_legale_id" => 250391551,
            "unite_legale" => {
              "id" => 250391551,
              "siren" => "219200235",
              "statut_diffusion" => "O",
              "unite_purgee" => nil,
              "date_creation" => "1980-01-01",
              "sigle" => nil,
              "sexe" => nil,
              "prenom_1" => nil,
              "prenom_2" => nil,
              "prenom_3" => nil,
              "prenom_4" => nil,
              "prenom_usuel" => nil,
              "pseudonyme" => nil,
              "identifiant_association" => nil,
              "tranche_effectifs" => "42",
              "annee_effectifs" => "2019",
              "date_dernier_traitement" => "2021-10-27T08=>11=>21",
              "nombre_periodes" => "7",
              "categorie_entreprise" => "ETI",
              "annee_categorie_entreprise" => "2019",
              "date_fin" => nil,
              "date_debut" => "2019-02-19",
              "etat_administratif" => "A",
              "nom" => nil,
              "nom_usage" => nil,
              "denomination" => "COMMUNE DE CLAMART",
              "denomination_usuelle_1" => nil,
              "denomination_usuelle_2" => nil,
              "denomination_usuelle_3" => nil,
              "categorie_juridique" => "7210",
              "activite_principale" => "84.11Z",
              "nomenclature_activite_principale" => "NAFRev2",
              "nic_siege" => "00014",
              "economie_sociale_solidaire" => "N",
              "caractere_employeur" => "O",
              "created_at" => "2022-04-03T02=>02=>23.707+02=>00",
              "updated_at" => "2022-04-03T02=>02=>23.707+02=>00",
              "etablissement_siege" => {
                "id" => 1585057487,
                "siren" => "219200235",
                "nic" => "00014",
                "siret" => "21920023500014",
                "statut_diffusion" => "O",
                "date_creation" => "1983-03-01",
                "tranche_effectifs" => "41",
                "annee_effectifs" => "2019",
                "activite_principale_registre_metiers" => nil,
                "date_dernier_traitement" => "2021-10-27T08=>11=>21",
                "etablissement_siege" => "true",
                "nombre_periodes" => "3",
                "complement_adresse" => "MAIRIE DE CLAMART",
                "numero_voie" => "1",
                "indice_repetition" => nil,
                "type_voie" => "PL",
                "libelle_voie" => "MAURICE GUNSBOURG",
                "code_postal" => "92140",
                "libelle_commune" => "CLAMART",
                "libelle_commune_etranger" => nil,
                "distribution_speciale" => nil,
                "code_commune" => "92023",
                "code_cedex" => "92141",
                "libelle_cedex" => "CLAMART CEDEX",
                "code_pays_etranger" => nil,
                "libelle_pays_etranger" => nil,
                "complement_adresse_2" => nil,
                "numero_voie_2" => nil,
                "indice_repetition_2" => nil,
                "type_voie_2" => nil,
                "libelle_voie_2" => nil,
                "code_postal_2" => nil,
                "libelle_commune_2" => nil,
                "libelle_commune_etranger_2" => nil,
                "distribution_speciale_2" => nil,
                "code_commune_2" => nil,
                "code_cedex_2" => nil,
                "libelle_cedex_2" => nil,
                "code_pays_etranger_2" => nil,
                "libelle_pays_etranger_2" => nil,
                "date_debut" => "2008-01-01",
                "etat_administratif" => "A",
                "enseigne_1" => "MAIRIE",
                "enseigne_2" => nil,
                "enseigne_3" => nil,
                "denomination_usuelle" => nil,
                "activite_principale" => "84.11Z",
                "nomenclature_activite_principale" => "NAFRev2",
                "caractere_employeur" => "O",
                "longitude" => "2.26263",
                "latitude" => "48.800409",
                "geo_score" => "0.88",
                "geo_type" => "housenumber",
                "geo_adresse" => "1 Place Maurice Gunsbourg 92140 Clamart",
                "geo_id" => "92023_6195_00001",
                "geo_ligne" => "G",
                "geo_l4" => "1 PLACE MAURICE GUNSBOURG",
                "geo_l5" => nil,
                "created_at" => "2022-04-03T05:09:36.298+02:00",
                "updated_at" => "2022-04-03T05:09:36.298+02:00",
                "unite_legale_id" => 250391551
              },
              "numero_tva_intra" => "FR81219200235"
            }
          }
      }
    when "88301031600015"
      {
        "etablissement" => {
          "id" => 1586647330,
          "siren" => "883010316",
          "nic" => "00015",
          "siret" => "88301031600015",
          "statut_diffusion" => "O",
          "date_creation" => "2018-05-06",
          "tranche_effectifs" => nil,
          "annee_effectifs" => nil,
          "activite_principale_registre_metiers" => nil,
          "date_dernier_traitement" => "2020-04-23T03=>48=>22",
          "etablissement_siege" => "true",
          "nombre_periodes" => "1",
          "complement_adresse" => "RED NEEDLES",
          "numero_voie" => "17",
          "indice_repetition" => nil,
          "type_voie" => "RUE",
          "libelle_voie" => "DE FRANCEVILLE",
          "code_postal" => "93220",
          "libelle_commune" => "GAGNY",
          "libelle_commune_etranger" => nil,
          "distribution_speciale" => nil,
          "code_commune" => "93032",
          "code_cedex" => nil,
          "libelle_cedex" => nil,
          "code_pays_etranger" => nil,
          "libelle_pays_etranger" => nil,
          "complement_adresse_2" => nil,
          "numero_voie_2" => nil,
          "indice_repetition_2" => nil,
          "type_voie_2" => nil,
          "libelle_voie_2" => nil,
          "code_postal_2" => nil,
          "libelle_commune_2" => nil,
          "libelle_commune_etranger_2" => nil,
          "distribution_speciale_2" => nil,
          "code_commune_2" => nil,
          "code_cedex_2" => nil,
          "libelle_cedex_2" => nil,
          "code_pays_etranger_2" => nil,
          "libelle_pays_etranger_2" => nil,
          "date_debut" => "2018-05-06",
          "etat_administratif" => "A",
          "enseigne_1" => nil,
          "enseigne_2" => nil,
          "enseigne_3" => nil,
          "denomination_usuelle" => nil,
          "activite_principale" => "70.22Z",
          "nomenclature_activite_principale" => "NAFRev2",
          "caractere_employeur" => "N",
          "longitude" => "2.542338",
          "latitude" => "48.886494",
          "geo_score" => "0.97",
          "geo_type" => "housenumber",
          "geo_adresse" => "17 Rue de Franceville 93220 Gagny",
          "geo_id" => "93032_1230_00017",
          "geo_ligne" => "G",
          "geo_l4" => "17 RUE DE FRANCEVILLE",
          "geo_l5" => nil,
          "created_at" => "2022-04-03T05=>16=>56.694+02=>00",
          "updated_at" => "2022-04-03T05=>16=>56.694+02=>00",
          "unite_legale_id" => 271172120,
          "unite_legale" => {
            "id" => 271172120,
            "siren" => "883010316",
            "statut_diffusion" => "O",
            "unite_purgee" => nil,
            "date_creation" => "2018-05-06",
            "sigle" => nil,
            "sexe" => "M",
            "prenom_1" => "PAUL",
            "prenom_2" => "JACQUES",
            "prenom_3" => "JEAN",
            "prenom_4" => nil,
            "prenom_usuel" => "PAUL",
            "pseudonyme" => nil,
            "identifiant_association" => nil,
            "tranche_effectifs" => nil,
            "annee_effectifs" => nil,
            "date_dernier_traitement" => "2020-04-23T03=>48=>22",
            "nombre_periodes" => "1",
            "categorie_entreprise" => "PME",
            "annee_categorie_entreprise" => "2019",
            "date_fin" => nil,
            "date_debut" => "2018-05-06",
            "etat_administratif" => "A",
            "nom" => "PIERRE",
            "nom_usage" => nil,
            "denomination" => nil,
            "denomination_usuelle_1" => nil,
            "denomination_usuelle_2" => nil,
            "denomination_usuelle_3" => nil,
            "categorie_juridique" => "1000",
            "activite_principale" => "70.22Z",
            "nomenclature_activite_principale" => "NAFRev2",
            "nic_siege" => "00015",
            "economie_sociale_solidaire" => nil,
            "caractere_employeur" => "N",
            "created_at" => "2022-04-03T03=>54=>05.205+02=>00",
            "updated_at" => "2022-04-03T03=>54=>05.205+02=>00",
            "etablissement_siege" => {
              "id" => 1586647330,
              "siren" => "883010316",
              "nic" => "00015",
              "siret" => "88301031600015",
              "statut_diffusion" => "O",
              "date_creation" => "2018-05-06",
              "tranche_effectifs" => nil,
              "annee_effectifs" => nil,
              "activite_principale_registre_metiers" => nil,
              "date_dernier_traitement" => "2020-04-23T03=>48=>22",
              "etablissement_siege" => "true",
              "nombre_periodes" => "1",
              "complement_adresse" => "RED NEEDLES",
              "numero_voie" => "17",
              "indice_repetition" => nil,
              "type_voie" => "RUE",
              "libelle_voie" => "DE FRANCEVILLE",
              "code_postal" => "93220",
              "libelle_commune" => "GAGNY",
              "libelle_commune_etranger" => nil,
              "distribution_speciale" => nil,
              "code_commune" => "93032",
              "code_cedex" => nil,
              "libelle_cedex" => nil,
              "code_pays_etranger" => nil,
              "libelle_pays_etranger" => nil,
              "complement_adresse_2" => nil,
              "numero_voie_2" => nil,
              "indice_repetition_2" => nil,
              "type_voie_2" => nil,
              "libelle_voie_2" => nil,
              "code_postal_2" => nil,
              "libelle_commune_2" => nil,
              "libelle_commune_etranger_2" => nil,
              "distribution_speciale_2" => nil,
              "code_commune_2" => nil,
              "code_cedex_2" => nil,
              "libelle_cedex_2" => nil,
              "code_pays_etranger_2" => nil,
              "libelle_pays_etranger_2" => nil,
              "date_debut" => "2018-05-06",
              "etat_administratif" => "A",
              "enseigne_1" => nil,
              "enseigne_2" => nil,
              "enseigne_3" => nil,
              "denomination_usuelle" => nil,
              "activite_principale" => "70.22Z",
              "nomenclature_activite_principale" => "NAFRev2",
              "caractere_employeur" => "N",
              "longitude" => "2.542338",
              "latitude" => "48.886494",
              "geo_score" => "0.97",
              "geo_type" => "housenumber",
              "geo_adresse" => "17 Rue de Franceville 93220 Gagny",
              "geo_id" => "93032_1230_00017",
              "geo_ligne" => "G",
              "geo_l4" => "17 RUE DE FRANCEVILLE",
              "geo_l5" => nil,
              "created_at" => "2022-04-03T05:16:56.694+02:00",
              "updated_at" => "2022-04-03T05:16:56.694+02:00",
              "unite_legale_id" => 271172120
            },
            "numero_tva_intra" => "FR51883010316"
          }
        }
      }
    else
      {
        "etablissement" => {
          "siren" => siret.first(9),
          "siret" => siret,
          "etat_administratif" => "A",
          "denomination_usuelle" => nil,
          "activite_principale" => "84.11Z",
          "unite_legale" => {
            "denomination" => "DEFAULT ORGANIZATION",
            "nom" => nil,
            "prenom_1" => nil,
            "prenom_2" => nil,
            "prenom_3" => nil,
            "prenom_4" => nil
          }
        }
      }
    end
  end
end
