name: Deployment via HTTPS (sandbox)

on:
  workflow_dispatch:
    branches:
      - '*'

jobs:
  deployment:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        host:
          - watchdoge3
          - watchdoge4
          - watchdoge5
      fail-fast: false
    environment: sandbox
    env:
      DEPLOY_HTTPS_LOGIN: ${{ secrets.DEPLOY_HTTPS_LOGIN }}
      DEPLOY_HTTPS_PASSWORD: ${{ secrets.DEPLOY_HTTPS_PASSWORD }}
      DEPLOY_HTTPS_REQUEST_URL: ${{ vars.DEPLOY_HTTPS_REQUEST_URL }}
      DEPLOY_HTTPS_RESPONSE_URL: ${{ vars.DEPLOY_HTTPS_RESPONSE_URL }}
      DEPLOY_HOST: host_${{ matrix.host }}
      DEPLOY_APP: datapass_sandbox
      DEPLOY_BRANCH: ${{ github.ref_name }}
    steps:
      - name: Download and run deploy script
        shell: bash
        run: |
          git clone https://github.com/etalab/api-entreprise-integration
          cd api-entreprise-integration
          ./deploy-parteprise.sh
